### ISSUE TITLE
Incorrect failure

### ISSUE THREAD

**Issue by dandv** [dorightdigital/amp-validator-web#1] opened 2016-02-12 09:29 UTC
http://m.folha.uol.com.br/amp/ilustrada/2016/02/1737908-adele-e-a-artista-que-mais-vendeu-discos-em-2015-diz-federacao.shtml is reported as failing, but the console shows `AMP validation successful` if run [in development mode](http://m.folha.uol.com.br/amp/ilustrada/2016/02/1737908-adele-e-a-artista-que-mais-vendeu-discos-em-2015-diz-federacao.shtml#development=1)

**Comment by nataliecarey** [comment] 2016-02-12 09:38
Indeed, I just reproduced it.  The AMP project has been under heavy development and it's changed since my lookup - I'll take a look at it but for now I'll take the interaction down and replace it with a link to the AMP project's semi-built-in command line validator ... I see you're having some problems there too https://github.com/ampproject/amphtml/issues/1967

**Comment by nataliecarey** [comment] 2016-02-12 09:39
Have you tried using https://github.com/ampproject/amphtml/pull/1554

**Comment by pietergreyling** [comment] 2016-02-12 09:47
Yep; please try to go as per docs here:
https://github.com/ampproject/amphtml/tree/master/validator
https://github.com/ampproject/amphtml/blob/master/validator/docs/building_a_command_line_amp_validator_for_mac_os_x.md

**Comment by nataliecarey** [comment] 2016-02-22 23:54
Web Validator is fixed now.  Your page validates http://www.amp-validator.com/validate?url=http%3A%2F%2Fm.folha.uol.com.br%2Famp%2Filustrada%2F2016%2F02%2F1737908-adele-e-a-artista-que-mais-vendeu-discos-em-2015-diz-federacao.shtml+&url=

**Closed as completed by nataliecarey** 2016-02-22 23:54 UTC
